version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gym_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password