version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 31667
    ports:
      - "5433:5432"
    networks:
      - app-network

  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gymApp.war:/usr/local/tomcat/webapps/gymApp.war
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge