version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 31667
    ports:
      - 61888:5432
#    volumes:
#      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network

  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - .app.war:/usr/local/tomcat/webapps/app.war
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge